cargo-features = ["profile-rustflags"]

[package]
name = "v_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
verifier = { path = "../src"}
cfg-if = "0.1.10"

[features]
default = []
